spring.application.name=springStart

# Database Configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com
spring.datasource.username=23fQu5n89q1UM7T.root
spring.datasource.password=5PXTTWOd1f0cZsJJ

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
