spring.application.name=springStart

# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.us-west-2.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY\

spring.datasource.username=2mp29sD1qFPt7E3.root
spring.datasource.password=czpo8zmqce90omIc

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Explicitly tell Hibernate to use MySQL dialect for TiDB
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
